language: node_js
node_js:
  - "node"
branches:
  only:
    - master
git:
  branch: master
before_script:
  - export NEW_VERSION=0.1.$TRAVIS_BUILD_NUMBER
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
script:
  - npm version $NEW_VERSION
before_deploy:
  - export GIT_TAG=v$NEW_VERSION
  - git add package.json
  - git commit -m "[CHORE] versioning - $TRAVIS_BUILD_NUMBER [skip ci]"
  - git push origin master
  - git tag $GIT_TAG -a -m "[CHORE] Tag build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$TAGPERM@github.com/stuisme/jasmine-pretty-html-reporter --tags
  - ls -R
deploy:
  provider: npm
  email: stuisme@gmail.com
  api_key: $NPM_TOKEN
  on:
    tags: false
    all_branches: true

